# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.  Please make changes
# to the host configuration in modules/hosts/laptop/default.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  # This will be regenerated during installation with the correct
  # hardware probe for the Framework Laptop 13 AMD.
  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # Filesystems, swap, LUKS mappings will be inserted here by
  # nixos-generate-config after partitioning.
  fileSystems."/" =
    { device = "/dev/disk/by-uuid/PLACEHOLDER";
      fsType = "btrfs";
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
