# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.
#
# NOTE: Filesystem definitions (fileSystems, swapDevices) have been REMOVED
# from this file. They are intentionally defined in:
#   modules/system/btrfs-laptop.nix
#
# After installation, if hardware changes, run:
#   sudo nixos-generate-config --root /mnt
# Then copy ONLY the hardware-specific sections (boot.*, nixpkgs.hostPlatform)
# into this file.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
