# Do not modify this file!  It was generated by 'nixos-generate-config'
# and may be overwritten by future invocations.
#
# NOTE: Filesystem definitions (fileSystems, swapDevices) have been REMOVED
# from this file. They are intentionally defined in:
#   modules/system/btrfs-laptop.nix
#
# After installation, if hardware changes, run:
#   sudo nixos-generate-config --root /mnt
# Then copy ONLY the hardware-specific sections (boot.*, nixpkgs.hostPlatform)
# into this file.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports = [ ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "thunderbolt" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  # LUKS device for the Btrfs root partition (nvme0n1p2)
  boot.initrd.luks.devices."cryptroot".device = "/dev/disk/by-uuid/48c54d72-5870-4287-9b82-30d61ae78c0e";

  swapDevices = [
    { device = "/dev/disk/by-partuuid/83c57e8f-1146-45b8-b1b4-e62fc0c3c055"; }
  ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
}
