#!/usr/bin/env bash
set -euo pipefail

# 07-copy-config.sh
# Copy the modular flake configuration into /mnt/etc/nixos/
#
# The repo already contains a correct hardware-configuration.nix with
# LUKS UUID and swap PARTUUID wired in. The file generated by
# nixos-generate-config is only used as a reference for kernel/initrd
# settings and is discarded after copy.

REPO="/home/nixos/nixos-config"
TARGET="/mnt/etc/nixos"

echo "=== Step 7: Copy flake to $TARGET ==="

# Clean target so old generated files don't leak
echo "Cleaning /mnt/etc/nixos..."
sudo rm -rf "$TARGET"/*
sudo rm -rf "$TARGET"/.* 2>/dev/null || true

# Copy the entire repo (including hidden files like .pi/, .gitignore)
echo "Copying flake from $REPO ..."
sudo tar -C "$REPO" -cf - . | sudo tar -C "$TARGET" -xf -

# Remove generated files that nixos-generate-config created at /mnt/etc/nixos root.
# The repo already has the correct hardware-config under modules/hosts/laptop/.
sudo rm -f "$TARGET/configuration.nix" "$TARGET/hardware-configuration.nix"

echo ""
echo "Flake copied to $TARGET"
echo ""
echo "Repo hardware-config (modules/hosts/laptop/hardware-configuration.nix)"
echo "already contains the LUKS UUID and swap PARTUUID."
echo ""
echo "Run ./08-install.sh"
